### ISSUE TITLE
Create developer documentation for all jobs

### ISSUE THREAD

**Issue by fbenduhn** [tthuem/FeatureIDE#151]
Create a list and description of all jobs that we create. Include information about the type of the job, e.g., whether it may block the UI.

**Comment by kTonscheidt** [comment]
https://github.com/tthuem/FeatureIDE/wiki/Jobs-in-FeatureIDE

**Comment by tthuem** [comment]
Looks nice, but we need additional information. For each job that is instantiated somewhere in FeatureIDE, we need the title shown to the FeatureIDE user and a description of what it is doing. Furthermore, we need the type of job (as listed in the wiki) for each job instance and the full-qualified class name that creates the job. A table for all of that could be a good idea.

**Comment by kTonscheidt** [comment]
So the actual tasks as I understand them are:
1. Title and description of each Job created by FeatureIDE should be shown during execution to the user.
2. Each **instance** of a job created in FeatureIDE should be added to the Jobs documentation in the wiki including
- The jobs type(class name)
- The fully qualified name of the instantiating class
- Information on whether this job may affect the UI ( == extends UIJob instead of Job (?))

There are roughly 200 calls to classes extending Job as well as about 80 calls to classes extending UIJob ( about half of those are anonymous ) and some of them might be instantiated multiple times.

I'd like to create a separate issue for the first task(since it is not documentation) and work on them simultaniously. 

Is this okay, or did i miss/misinterpret something?

**Comment by tthuem** [comment]
I'm not talking about any changes to the source code of FeatureIDE. Regarding 1., all jobs should already have titles shown to the user. Regarding 2., it is correct, but we need title and description in addition (in the wiki).

**Comment by kTonscheidt** [comment]
update: UIJobs are done.
todo: other Jobs; Table layout in wiki
