### ISSUE TITLE
Feature model edits view is opened in the resource perspective

### ISSUE THREAD

**Issue by tthuem** [tthuem/FeatureIDE#207]
When creating a new workspace, the default perspective is the resource perspective. But it does not make sense to show our view in this perspective. Our own perspective should remain as usual.

**Comment by skrieter** [comment]
There is an explicit extension to show this view in the resource perspective (Removing it fixes this issue).
I think this was done, because the FeatureIDE perspective is introduced in the UI plugin and the edits view in fm.ui.
Should we move the extension for the FeatureIDE perspective into the fm.ui plugin as well?

**Comment by tthuem** [comment]
No, simply remove this view from the resource perspective. Users may open it, when they need it. It should only be openened in the FeatureIDE perspective per default.
