### ISSUE TITLE
Problem during opening a feature model in a new system (new workspace)

### ISSUE THREAD

**Issue by suhail-a** [tthuem/FeatureIDE#209]
Hello,

I am studying in a University in Germany and I am doing a project to built a feature model for a Hybrid vehicle on "eclipse4.2-featureide2.7.0-win32". I encountered a problem when I was trying to open a feature model (that was built in another system and another workspace) into a new system with a new workspace. I am not able to import/ open/ transfer my feature model (that I built in the old system) into my new system (PC). Please advice.

**Comment by tthuem** [comment]
We are currently clarify the issue via email. More on this soon.

**Comment by tthuem** [comment]
The problem is that a model was created with a newer version of FeatureIDE and loaded with an older version. In this older version, one of the new tags (tautology) was not yet supported. Removing the tag manually and it should be possible to import/load the feature model.

This issue cannot be prevented in old version, but we need a new concept to avoid such situations in future version, whenever possible. See #187, FM Parser should distinguish between warnings and errors

**Comment by suhail-a** [comment]
Hi,
Thanks for the help but I have a few more doubts-
1. Can I copy features from one model into another model? If so, how?
2. How can I connect two features which are not part of the same compound feature above? Is there a possibility to include "Requires and Excludes" links between features?

**Comment by tthuem** [comment]
> 1. Can I copy features from one model into another model? If so, how?
Yes, but only by copy and paste in the source tab / XML representation. No one requested this so far for the feature diagram. :)

> 2. How can I connect two features with "Requires and Excludes" links as shown in the figure attached with this email?

We have no graphical representation of them so far. However, you can simply create cross-tree constraints with the same meaning:
* A requires B is equivalent to A implies B
* A excludes B is equivalent to not A or not B

Hope this helps,
Thomas
