### ISSUE TITLE
Initialize all strings of each plug-in statically in a separate class

### ISSUE THREAD

**Issue by tthuem** [tthuem/FeatureIDE#228]
Currently, the messages shown to the user are distributed over the complete code base. The idea is to have them on one place (at least for each plug-in), to improve consistency more easily. I would like to improve consistency afterwards.

**Comment by pinnecke** [comment]
There are approx. 12.000 strings in the entire project. When moving them into a "StringTable" by hand, this will take at least 100h (consider there are certain situations such that "copy and paste" does not work  directly, avoiding duplicate entries or broken text... being tired after 100x copy and paste). What about the following idea: Using a little quick-written tool, we could automatically scan the entire project, extract strings, replace them with static variables and collect those static variables per-plugin in a "StringTable" static class.

**Comment by fbenduhn** [comment]
What about the refactoring support of eclipse? Doesnt it help?

**Comment by tthuem** [comment]
Table for each plug-in sounds great. Whatever is fast and gets you to the result is fine to me.

**Comment by pinnecke** [comment]
Currently, I extracted (read-only) each string occurrence in each FeatureIDE plugin into a [string extraction overview file](http://pinnecke.com/realm/FeatureIDE/string_table/stringtable.csv). This file shows
* The actual string
* The number of duplicates
* The related source files + line number
* A possible identifier for a static variable

If a string occurs over several source files, these strings are combined into one static variable identifier.

However, I propose to take this file as starting point, how to go further. We should discuss several topics, before I will continue. This includes:

1. Not all strings have to be extracted, e.g., "-D". We need a rule that allows excluding such strings. Ideally with less effort
2. Some string are very similar and we need a rule, how to handle and encode these strings. For instance "Constraint" and "constraint" aren't combined currently, since they cannot be combined into one constant because the difference is related to some context. The corresponding constant name is "CONSTRAINT" and "CONSTRAINT_" currently.
3. We can put all constants into one public interface in e.g. fm.core. One alternative is a per-plug-in interface. The first leads to a "god" class, that is highly accessed by nearly all classes but redundancy is low. The latter avoids this huge binding, but leads to potential redundancy (consider the string "constraint" that will occur in more than one plug-in table). Another possibility is to use both approaches at once. Therefore, unique strings are in per-plug-in tables and strings that are shared by more than one plugin are put into the fm.core class. However, the latter approach seems to find a good balance but is hard to maintain and potentially harder to realize.
4. Assume each  string is now extracted into one or more string tables. How to avoid, that hard coded strings are generated in future? One way is to add constants directly during development (in responsibility of each developer). Another way is to extend the "extraction script" into some tool, that can be applied in future. When doing so, there are other aspects that we should discuss.
5. If one has to find a certain string inside the string table (in order to avoid string duplicates), it might be stressing. One can image a tool, that does a suggestion of several existing constants, given a developers custom string. However, this touches a bit of information retrieval but should be considered.

**Comment by tthuem** [comment]
1. probably not useful to automate
2. constants should be revised anyway manually
3. even if there is one class for each plug-in, I don't see a need to have multiple occurrences of the same string. we can just access it from one of the used plug-ins.
4. just run the script from time to time should be sufficient.
5. not crack a nut with a sledgehammer: CTRL+F should be sufficient to identify whether there is an appropriate string.

**Comment by pinnecke** [comment]
I reduced the size to 880 records by some exclusions-rules and filtering via heuristic, see [extracted files](http://pinnecke.com/realm/FeatureIDE/string_table/stringtable2.txt). This should be a good start to go further. More details in the next team meeting.

**Comment by tthuem** [comment]
Please also fix that duplicated occurrence of 'hidden':

![zwischenablage-1](https://cloud.githubusercontent.com/assets/5330357/8541260/1c053822-248d-11e5-9720-6bca97c49043.png)

**Comment by pinnecke** [comment]
See **remote branch issue_288**. Please review, comment and resign to me afterwards.

There are around 980 "reasonable" strings extracted in `de.ovgu.featureide.fm.core.localization.StringTable`. All tests pass.

**Comment by tthuem** [comment]
Good job! I fixed some spelling mistakes and found some further things marked with TODO. Please have a look at them.

**Comment by pinnecke** [comment]
I took a look at the TODOs and clarified the strings. Please review, comment and reassign me afterwards (such that I will merge the changes into master branch)

**Comment by tthuem** [comment]
Think that there's no need for another review. Please go ahead an merge it.

**Comment by pinnecke** [comment]
Merged into master branch.
