### ISSUE TITLE
Refactor fm.core.Features class

### ISSUE THREAD

**Issue by meinicke** [tthuem/FeatureIDE#279]
The fm.core.Features class should be removed and the method should either refactored to fm.core.Feature or into a utils class at fm.core.utils

**Comment by pinnecke** [comment]
Moved the utility method into `feature` class and refactored `feature` class, since the `feature` class constrains (at least) three chunks of different responsibilities that shouldn't be in mixed in one class. 

Therefore, I extracted inside the class `feature` the following nested classes

1. *Properties*, 
2. *ModelContext* and 
3. *Graphics* 

I grouped the related methods and fields. As a consequence, the old methods are now annotated as *deprecated*.

All tests passes on my machine. Please check and review, if everything is alright reassign this issue to me. I will merge it into master (after discussion in next team meeting)

#### Before refactoring
``` java
Feature feature = new Feature(...);

List<Feature> children = feature.getChildren();
GraphicItem image = feature.getItemType();
boolean isAbstract = feature.isAbstract();
Feature parent = feature.getParent();
Collection<Constraint> relevantConstrains = feature.getRelevantConstraints()
FMPoint point = feature.getLocation();
boolean isHidden = feature.isHidden();
```

#### After refactoring
``` java
Feature feature = new Feature(...);

Feature.ModelContext context = feature.getContext();
Feature.Properties properties = feature.getProperties();
Feature.Graphics graphics = feature.getGraphicalRepresentation();

boolean isAbstract = properties.isAbstract();
boolean isHidden = properties.isHidden();

List<Feature> children = context.getChildren();
Feature parent = context.getParent();
Collection<Constraint> relevantConstrains = context.getRelevantConstraints()

GraphicItem image = graphics.getItemType();
FMPoint point = graphics.getLocation();
```

**Comment by meinicke** [comment]
I cannot compile the file Feature as PropertyChangedEventListener cannot be found

The file FeatureS still exists:
"The fm.core.Features class should be removed and the method should either refactored to fm.core.Feature or into a utils class at fm.core.utils"

I dont know if the current refactoring of Feature makes the implementation any better as it currently requires twice as much LOC.
You may want to extract the inner classes.

**Comment by pinnecke** [comment]
* Added missing class `PropertyChangedEventListener.java`. Should compile now.
* Removed `Features.java` class since it is obsolet

Both missing actions were caused due to problems with my working copy (180+ changed items because of line ending issues (see meeting)). However, it should compile now.

The current refactoring of `Feature`class extracts responsibilities into nested sub classes and, hence, the mixture of properties, context related functionality, and graphics stuff, are no longer in direct control of `Feature`. As it is with refactoring, this only improves the software design (and might be an step towards an `FeatureInterface` as mentioned by Sebastian). However, the LOC is that high since the old methods are still existing although marked as deprecated. When removing them, `Feature` will contain around 800 LOC (which includes the main class as well as the three nested classed) (compared to around 720 LOC before, it's not that high but supports improved maintainability, understandability and ...). The inner classes are directly related to `Feature` class and should be connected to the main class. Therefore, an inner class is reasonable here (although not necessary). On the one hand, all three classes should be in the same *namespace* as feature, but due to the missing support of namespaces in java, nested classed can be used. On the other hand, no other class will use them directly as part of its own implementation and, hence, a "top-level" class for properties, graphics and model context is not needed.

**Comment by pinnecke** [comment]
Please test and review. Next steps should be discussed in next team meeting in context of `FeatureInterface`.

**Comment by pinnecke** [comment]
Seems the feature diagram draws connections between features always to to upper left corner of the canvas. Any ideas?
